### ISSUE TITLE
Building a react app using redux

### ISSUE THREAD

**Issue by lutherdexter** [ahamedfazil/react-redux-ts-sp#9]
Hi, I came across your project while doing some reach on a project I'm working on and I'm a big fan of how you structured the project  

I am building a SharePoint react app using redux. The app will be hosted/deployed on-premise SP13. Alongside some pure redux stuff, I'm adopting your approach re: using interfaces for models, actions etc .

I have a small issue: I'm getting a TypeError: Cannot read property ' ' of undefined. It appears my container isn't passing the properties correctly to the form. Like you, when I try to Dispatch my props with <IStore> I get error:
 ```
Type 'IStore' does not satisfy the constraint 'Action<any>'.
  Property 'type' is missing in type 'IStore' but required in type 'Action<any>'.
```

It then says my actions are not assignable to parameter of type 'ActionCreatorsMapObject<any>'.

Do you know what I'm doing wrong?

**Comment by lutherdexter** [comment]
The error 

`
![image](https://user-images.githubusercontent.com/46234351/55679552-9457c780-5905-11e9-996d-b2515a8ee6b2.png)
`

**Comment by ahamedfazil** [comment]
Hi Luther,

As per our internal discussion, this issue happened because of different version of redux @types/redux that's been used in the project. Please make sure the version is same as the project in the repository.

Closing this issue since we sorted out the issue,
